### ISSUE TITLE
Please create a new release for amazon linux

### ISSUE THREAD

**Issue by isukapalli** [treasure-data/chef-td-agent#127]
We have an issue trying to install td-agent 3 with the current cookbook.
This issue is fixed https://github.com/treasure-data/chef-td-agent/pull/122 and this is the latest commit id https://github.com/treasure-data/chef-td-agent/commit/7320ded3b486d8f8305888ca762b9b64812c2bad
Please release new version of td-agent in **supermarket** to consume by end users.

**Note:** We were able to install td-agent 3 by referring this commit in Berksfile
```
cookbook "td-agent", git: "https://github.com/treasure-data/chef-td-agent.git", ref: "7320ded3b486d8f8305888ca762b9b64812c2bad"
```

```
[kitchen@a460106e3f77 ~]$ sudo yum info td-agent
Loaded plugins: ovl, priorities
Installed Packages
Name        : td-agent
Arch        : x86_64
Version     : 3.3.0
Release     : 1.amazon2018.03
Size        : 148 M
Repo        : installed
From repo   : treasure-data
Summary     : Treasure Agent: A data collector for Treasure Data
URL         : http://treasuredata.com
License     : Unspecified
Description : Treasure Agent: A data collector for Treasure Data
```

**Comment by yyuu** [comment]
Now 3.1.0 should be available there.

https://supermarket.chef.io/cookbooks/td-agent/versions/3.1.0
