### ISSUE TITLE
td_agent_match duplicated parameters attributes

### ISSUE THREAD

**Issue by scalp42** [treasure-data/chef-td-agent#129]
Hi @yyuu 

I'm trying to replicate the [following](https://github.com/fluent/fluentd/issues/1110#issuecomment-233309012):

```
<match elasticsearch file>
  @type copy
  <store>
     @type elasticsearch
  </store>
  <store>
     @type file
  </store>
</match>
```

As you can see, the issue is that `store` is duplicated here:

```ruby
td_agent_match 'elasticsearch' do
  type 'copy'
  tag 'elasticsearch file'
  parameters(
    store: {
      '@type': 'elasticsearch'
    },
    store: {
      '@type': 'file'
    }
  )
end
```

Do you have any ideas how to work around this issue?

**Comment by kkjeiyth** [comment]
Hi @scalp42 

I still have not tested, but I think parameters of `td_agent_match` support input array for `store`.
So could you try pass one array to `store` instead of using `store_*` in #130 ?
```
td_agent_match 'elasticsearch' do
  type 'copy'
  tag 'elasticsearch file'
  parameters(
    store: [{'@type': 'elasticsearch'},
                {'@type': 'file'}]
  )
end
```

**Comment by scalp42** [comment]
@kkjeiyth good catch I tried passing an array to `parameters` but not an array to `store`.

Let me try right now and I'll update.

**Comment by scalp42** [comment]
@kkjeiyth it works, thanks a lot! I'll close my PR then as it's useless 😅
