### ISSUE TITLE
yum repository for version 2.x can't access from AWS EC2 instance.

### ISSUE THREAD

**Issue by hirakiuc** [treasure-data/chef-td-agent#46]
I tried to apply this cookbook my EC2 instance to install td-agent 2.1.5-0 by pinning attribute, but error raised like below.

```
[2015-03-12T17:51:14+09:00] ERROR: yum_repository[treasure-data] (td-agent::default line 76) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-treasure-data] (/var/chef/cache/cookbooks/yum/providers/repository.rb line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of yum -q makecache --disablerepo=* --enablerepo=treasure-data ----
STDOUT:
STDERR: http://packages.treasuredata.com/2/redhat/latest/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
```

I checked these things...

- The URL `http://packages.treasuredata.com/2/redhat/latest/x86_64/repodata/repomd.xml` respond `NoSuchKey` xml.
  - The yum repository does not have `latest` entry. ([here](https://shrub.appspot.com/packages.treasuredata.com/2/redhat/))
  - `/etc/yum.conf` on my EC2 instance contains `releasever=latest` line. ([code](https://github.com/treasure-data/chef-td-agent/blob/master/recipes/default.rb#L73))

Should I change `releasever=7` on my EC2 instance or install by other method ?

(I hope that the repository has `latest` entry on `http://packages.treasuredata.com/2/redhat/`...)

**Comment by yyuu** [comment]
What distro are you using? Amazon Linux?

**Comment by hirakiuc** [comment]
> What distro are you using? Amazon Linux?

Yes.

The EC2 instance created with `Amazon Linux AMI 2014.09.2 (HVM) - ami-18869819`.

**Comment by yyuu** [comment]
@repeatedly What if we release RPM packages to [latest](http://packages.treasuredata.com/2/redhat/latest) as well? I think it would help improving `td-agent2`'s support for Amazon Linux.

In my understanding, Amazon Linux is one of popular distro on EC2 and we should improve the support for them.

**Comment by repeatedly** [comment]
@yyuu One concern is Amazon Linux doesn't have binary compatibility with RHEL/CentOS because they have own version policy since latest release.
It causes hard to guarantee our RPM work on Amazon Linux.
In addition, we don't have a Amazon Linux image so automatic packaging is too hard.

I tried to create redirection rule for Amazon Linux but S3 + CloudFront combination has a limitation for redirection(latest -> 7).
I'm not sure we should create RPM for Amazon Linux because it needs extra cost.
BTW, setup latest directory is not difficult.

**Comment by yyuu** [comment]
@repeatedly I understood that the difficulty to support Amazon Linux is binary compatibility issue.... To deal with this issue for now, I think there would be 2 ways. I believe the former is better. Which one would you like, or other options?

1. Support Amazon Linux _unofficially_ with using as same binary as RHEL7/CentOS7
  * Create copy of binaries in `latest` directory
1. Remove support for Amazon Linux from `chef-td-agent`

**Comment by repeatedly** [comment]
After tried https://github.com/mitchellh/vagrant-aws, we should select 1.
I'm in fossasia event so I can't test above right now.

**Comment by repeatedly** [comment]
td-agent 2.2.0 provides Amazon Linux RPM.
This issue should be resolved.

**Comment by hirakiuc** [comment]
Thanks !

This cookbook works with td-agent 2.2.0.
