### ISSUE TITLE
URL returns 404 when setting up yum repo

### ISSUE THREAD

**Issue by bsdtrhodes** [treasure-data/chef-td-agent#52]
This is the log; however, following the repo to the Amazon s3 site still causes issues.  Even hard coding the URL in the recipes/default.rb file will lead to continued failure.

[2015-05-07T15:59:06-04:00] DEBUG: providers that survived replacement include: [Chef::Provider::Execute]
http://packages.treasuredata.com/2/redhat/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: treasure-data. Please verify its path and try again

      
      ================================================================================
      Error executing action `run` on resource 'execute[yum-makecache-treasure-data]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=treasure-data ----
      STDOUT: 
      STDERR: http://packages.treasuredata.com/2/redhat/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
      Trying other mirror.
      Error: Cannot retrieve repository metadata (repomd.xml) for repository: treasure-data. Please verify its path and try again
      ---- End output of yum -q makecache --disablerepo=* --enablerepo=treasure-data ----
      Ran yum -q makecache --disablerepo=* --enablerepo=treasure-data returned 1
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/yum/providers/repository.rb
      
       61:   execute "yum-makecache-#{new_resource.repositoryid}" do
       62:     command "yum -q makecache --disablerepo=* --enablerepo=#{new_resource.repositoryid}"
       63:     action :nothing
       64:     only_if { new_resource.enabled }
       65:   end
       66: 
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/yum/providers/repository.rb:61:in `block in class_from_file'
      
      execute("yum-makecache-treasure-data") do
        action [:nothing]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "yum -q makecache --disablerepo=* --enablerepo=treasure-data"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "td-agent"
        only_if { #code block }
      end

**Comment by yyuu** [comment]
Which distribution are you using? It seems that the `$releasever` on your platform is `6Server` and it would be cause. I confirmed that the recipe is working expectedly on CentOS 6.6 where the `$releasever` is `6`, not `6Server`.

Please let me know the following information for further investigation.

1. The distribution you're using
2. Output from `python -c 'import json,yum;yb=yum.YumBase();print(json.dumps(yb.conf.yumvar,indent=4))'`

**Comment by bsdtrhodes** [comment]
I forgot about this, sorry.  Everything is working fine now, you can close
