### ISSUE TITLE
td_agent_gem package provider broken

### ISSUE THREAD

**Issue by TheFurya** [treasure-data/chef-td-agent#55]
Currently the td_agent_gem provider does not work with the newest chef versions. There seems to be an update to the package provider, which broke the td_agent_gem provider. Here is a link to the log output: https://gist.github.com/eightbitraptor/0099e6cfb6a54333951b

I tested it with chef 12.2.1 and it stills works in that version, but it seems broken in 12.3.0. I will try to find the change that broke that in the chef package provider and add it to this issue.

**Comment by yyuu** [comment]
Isn't it the same issue as #50 and #51?

**Comment by TheFurya** [comment]
Oh, yes, you are correct. I will close this one then.
