### ISSUE TITLE
Broken version

### ISSUE THREAD

**Issue by fabiokr** [treasure-data/chef-td-agent#64]
Tried to install on Ubuntu 14.04, was getting this error:

```
STDERR: E: Version '2.2.1' for 'td-agent' was not found
```

Setting these attributes fixed it:

```
default[:td_agent][:pinning_version] = true
default[:td_agent][:version] = '2.2.1-0'
```

**Comment by yyuu** [comment]
There might be some problem when you try installing it. Though I couldn't reproduce.

We're testing cookbooks on Ubuntu 14.04 as well and it is just working fine. It must not be an issue of recipe implementation at least.

https://github.com/treasure-data/chef-td-agent/blob/9a7f3f7306841ab317f02923806b8a9be1d4cb84/.kitchen.yml#L24-L29
