### ISSUE TITLE
release updated version to Supermarket

### ISSUE THREAD

**Issue by domofactor** [treasure-data/chef-td-agent#76]
hey guys,

this recent commit(42432a91a74c000ac51e6d70bbb8768b1a450a2f) is pretty useful. so, seeing as its a feature update, it would be great to see a new version released and uploaded up to the Supermarket. 

Thanks!

**Comment by yyuu** [comment]
Ah, okay. I'll do it today or tomorrow....

**Comment by yyuu** [comment]
I've just released v2.2.0 on the supermarket. Please let me know if there's problem.

https://supermarket.chef.io/cookbooks/td-agent/versions/2.2.0

Cheers
