### ISSUE TITLE
Alternative user to td-agent

### ISSUE THREAD

**Issue by FenrirUnbound** [treasure-data/chef-td-agent#78]
For context, our production environment only allows an approved set of system users. We currently are utilizing the `/etc/sysconfig/td-agent` to have the process be started as a different user, but it does not change the permissions of various files and folders. The difference in ownership disallows the process from being restarted.

Would you be open to allowing the td-agent user to be an attribute instead of hard-coded in the recipe? We wanted to contribute with a PR, but wanted to see if the work is worth pursing if you would allow it.

**Comment by yyuu** [comment]
@FenrirUnbound obviously it'd be better to avoid hard-coded user and groups. PR's welcome!

**Comment by FenrirUnbound** [comment]
Fixed in PR #80
